services:

  mysql_1:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
#    volumes:
#      - ./docker/mysql:/var/lib/mysql/data
    environment:
      - MYSQL_ROOT_PASSWORD=admincalculator
      - MYSQL_USER=usercalculator
      - MYSQL_PASSWORD=calculator

#  You need to manually created the directory ./docker/msyql
